openapi: 3.0.0
info:
  title: Stock Management API
  description: stock management api details
  version: 1.0.0

servers:
  - url: http://localhost:3000/
    description: Local host server
paths:
  /auth/login:
    post:
      summary: Sample endpoint
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
components:
  schemas:
    LoginResponse:
      type: object
      description: response after login
      properties:
        access_token:
          type: string
